bytecodealliance/jco

- src/cmd/opt.js
- src/common.js
Adds a total summary line to the component optimization core binary report.
> feat: opt summary total

- Cargo.lock
- Cargo.toml
- crates/js-component-bindgen-component/Cargo.toml
- crates/js-component-bindgen-component/src/lib.rs
- crates/js-component-bindgen/Cargo.toml
- crates/wasm-tools-component/Cargo.toml
- crates/wasm-tools-component/src/lib.rs
- package.json
Updates the self-build to the latest toolchain.
> build: update to latest self-build

- crates/wasm-tools-component/src/lib.rs
Removes unnecessary resolver code for the new `select_world` function.
> fix: use select_world

- packages/preview2-shim/lib/nodejs/environment.js
- packages/preview2-shim/lib/nodejs/filesystem.js
- packages/preview2-shim/lib/nodejs/monotonic-clock.js
- packages/preview2-shim/lib/nodejs/wall-clock.js
- test/codegen.js
- test/runtime.js
- test/test.js
Updates the preview2-shim to the latest API forms.
> fix: preview2 latest APIs

- packages/preview2-shim/lib/http/wasi-http.js
This will add the emulated future to WASI HTTP that will resolve immediately.
> feat(preview-shim): add emulated future to wasi http

- Cargo.lock
- Cargo.toml
- test/api.js
- test/cli.js
Updates to latest wit-bindgen toolchain.
> deps: toolchain update

- src/cmd/componentize.js
Resolves https://github.com/bytecodealliance/jco/issues/71.
> fix: componentize import error filter

- README.md
- src/cmd/componentize.js
- src/jco.js
Updates the `jco componentize` command to the latest componentize API as per https://github.com/bytecodealliance/componentize-js/pull/24.
> feat: latest componentize api

- src/jco.js
> Another version update to 0.8.0 in jco.js

- crates/js-component-bindgen/src/ts_bindgen.rs
Fixes the missing handling for anonymous export interface generation in the TypeScript typing bindgen.
> fix: anon interface typescript generation

- crates/js-component-bindgen/src/esm_bindgen.rs
- crates/js-component-bindgen/src/transpile_bindgen.rs
- packages/preview2-shim/lib/browser/cli-base.js
- packages/preview2-shim/lib/browser/clocks.js
- packages/preview2-shim/lib/browser/http.js
- packages/preview2-shim/lib/browser/io.js
- packages/preview2-shim/lib/browser/logging.js
- packages/preview2-shim/lib/browser/poll.js
- packages/preview2-shim/lib/browser/random.js
- packages/preview2-shim/lib/browser/sockets.js
- packages/preview2-shim/lib/nodejs/cli-base.js
- packages/preview2-shim/lib/nodejs/clocks.js
- packages/preview2-shim/lib/nodejs/filesystem.js
- packages/preview2-shim/lib/nodejs/http.js
- packages/preview2-shim/lib/nodejs/io.js
- packages/preview2-shim/lib/nodejs/logging.js
- packages/preview2-shim/lib/nodejs/poll.js
- packages/preview2-shim/lib/nodejs/random.js
- packages/preview2-shim/lib/nodejs/sockets.js
Includes some fixes for the latest ComponentizeJS support.
> Componentize Upgrade

- Cargo.lock
- Cargo.toml
Upgrades to the latest Wasmtime release.
> deps: upgrade to Wasmtime@10.0.1

- crates/js-component-bindgen/src/esm_bindgen.rs
- crates/js-component-bindgen/src/ts_bindgen.rs
Fixes kebab function import support, both typing and runtime cases and adds a test to avoid regressions.
> fix: kebab function imports

- crates/js-component-bindgen/src/transpile_bindgen.rs
Chatted with @alexcrichton a bit about [https://github.com/bytecodealliance/jco/issues/109](https://github.com/bytecodealliance/jco/issues/109) and he helped me put this together.
> instance flags

- package.json
- test/cli.js
Reenables this test now that 0.2.0 is out.
> test: reenable componentize test

- packages/preview2-shim/lib/browser/cli.js
- packages/preview2-shim/lib/nodejs/cli.js
Updates the remaining WASI CLI interfaces in the preview2-shim implementation.
> fix: wasi cli interfaces

- crates/wasm-tools-component/src/lib.rs
- crates/wasm-tools-component/wit/wasm-tools.wit
- packages/preview2-shim/lib/browser/cli.js
- packages/preview2-shim/lib/browser/filesystem.js
- packages/preview2-shim/lib/browser/io.js
- packages/preview2-shim/lib/browser/poll.js
- src/api.js
- src/cmd/opt.js
- src/cmd/run.js
- src/cmd/wasm-tools.js
- update-wasi.sh
This extends browser WASI interfaces to support a virtual filesystem and stdio streams.
> feat: extend browser wasi support

- .gitmodules
- xtask/src/main.rs
- xtask/src/test.rs
Reuses wasmtime's conformance test suite. Closes #178.
> Exercise wasmtime conformance tests

- crates/js-component-bindgen/src/function_bindgen.rs
This fixes incorrect guest code generation in cases of aliased resources.
> use name of dealiased resource type when lifting/lowering handles

- crates/js-component-bindgen/src/function_bindgen.rs
- packages/preview2-shim/lib/browser/cli.js
- packages/preview2-shim/lib/browser/filesystem.js
- packages/preview2-shim/lib/browser/index.js
- packages/preview2-shim/lib/browser/io.js
- packages/preview2-shim/lib/nodejs/cli.js
- packages/preview2-shim/lib/nodejs/filesystem.js
- src/cmd/run.js
Fixes the browser shim which broke during recent IO upgrades. Resolves https://github.com/bytecodealliance/jco/issues/246.
> fix: browser shim

- crates/js-component-bindgen-component/src/lib.rs
- crates/js-component-bindgen/src/core.rs
- crates/js-component-bindgen/src/esm_bindgen.rs
- crates/js-component-bindgen/src/files.rs
- crates/js-component-bindgen/src/function_bindgen.rs
- crates/js-component-bindgen/src/names.rs
- crates/js-component-bindgen/src/transpile_bindgen.rs
- crates/js-component-bindgen/src/ts_bindgen.rs
- crates/wasm-tools-component/src/lib.rs
- xtask/src/build/jco.rs
- xtask/src/generate/tests.rs
- xtask/src/update/preview2.rs
`cargo clippy` wasn't happy. Now it's happier.
> chore: Make Clippy happier

- crates/js-component-bindgen/src/ts_bindgen.rs
Fixes a bug with resource type aliasing.
> fix: resource type aliasing

- packages/preview2-shim/lib/nodejs/filesystem.js
Adds a directory error for fs advise.
> fix: fs advise directory error

- packages/preview2-shim/lib/browser/filesystem.js
Possible fix for https://github.com/bytecodealliance/jco/pull/301.
> Fix: browser traverse

- packages/preview2-shim/lib/io/worker-http.js
- packages/preview2-shim/lib/io/worker-io.js
- packages/preview2-shim/lib/io/worker-thread.js
- packages/preview2-shim/lib/nodejs/http.js
- tests/generated/proxy_hash.rs
- tests/server/index.js
- tests/virtualenvs/server-api-proxy-streaming.js
- xtask/src/generate/tests.rs
This completes the incoming handler test cases, finishing the HTTP implementation.
> fix: complete HTTP incoming handler tests

- packages/preview2-shim/lib/io/worker-socket-tcp.js
- packages/preview2-shim/lib/nodejs/sockets/socket-common.js
- packages/preview2-shim/lib/nodejs/sockets/tcp-socket-impl.js
- packages/preview2-shim/lib/nodejs/sockets/udp-socket-impl.js
Related https://github.com/bytecodealliance/jco/issues/315
> chore: preview2_tcp_connect passing

- crates/js-component-bindgen/src/transpile_bindgen.rs
- test/api.js
Resolves #324 in supporting maps into package imports specifiers.
> fix: imports mappings

- packages/preview2-shim/lib/io/worker-thread.js
The finish state on polls was needed when we needed to be able to separately determine the closed state from the poll state, but now that the poll state references the underlying stream, this information can be obtained directly from the underlying stream.
As a result, we no longer need a three state poll, but can simplify back to a binary resolve and unresolved state system.
> wasi: refactor out finish state on poll

- crates/js-component-bindgen/src/ts_bindgen.rs
- test/cli.js
- test/fixtures/wit/deps/ts-check/ts-check.wit
- update-wasi.sh
Resolves https://github.com/bytecodealliance/jco/issues/342.
> fix: ts naming cases

- .github/workflows/main.yml
- .gitignore
- packages/preview2-shim/lib/io/worker-sockets.js
- packages/preview2-shim/lib/nodejs/filesystem.js
- tests/virtualenvs/scratch.js
- xtask/src/generate/tests.rs
Adds Windows to the Preview2 Conformance CI
Work-in-progress, pending the following test cases:
> ci: Windows Preview2 Conformance

- crates/js-component-bindgen/src/ts_bindgen.rs
- test/api.js
- test/fixtures/wits/issue-365/issue-365.wit
- test/typescript.js
Resolves https://github.com/bytecodealliance/jco/issues/365.
> fix: ts root pathing distinctions

- docs/src/introduction.md
- docs/src/transpiling.md
Adds some initial documentation on transpilation.
> docs: transpiling documentation

- crates/js-component-bindgen/src/names.rs
> fix(js-component-bindgen): missing eval keyword

- crates/js-component-bindgen/src/function_bindgen.rs
This fix follows-on from https://github.com/bytecodealliance/jco/pull/380, fixing support for automatic resource borrow dropping in ComponentizeJS generated function calls. In the process this exposed a bug in the JCO drop checker itself, which is also fixed here.
> fix: ComponentizeJS drop support, and drop checks

- Cargo.lock
- Cargo.toml
- test/api.js
- test/cli.js
> deps: update wit bindgen

- crates/js-component-bindgen/src/function_bindgen.rs
- crates/js-component-bindgen/src/transpile_bindgen.rs
This updates the resource method calls for JS-defined resources to use `resource.method(arg)` instead of `ResourceClass.prototype.method.call(resource, arg)` allowing more flexibility in dynamic subclassing of JS resources.
My main concern is that this doesn't apply to the `constructor` or static methods, creating a divergence in behaviour.
Let's discuss this at the next Jco meeting actually, I still think it might make sense not to land this.
> feat: JS resource method dynamic dispatch

- crates/js-component-bindgen/src/function_bindgen.rs
- crates/js-component-bindgen/src/transpile_bindgen.rs
- docs/src/optimized-host-bindings.md
- package.json
- test/cli.js
- test/helpers.js
- test/preview2.js
Resolves https://github.com/bytecodealliance/jco/issues/396 where handle table indexing was being overridden for exported resources.
> fix: handle table indexing

- packages/preview2-shim/types/clocks.d.ts
The type definitions for the clocks were swapped
> fix: clocks type definitions

- .github/workflows/main.yml
- .gitignore
- lib/console.js
- package-lock.json
- package.json
- src/cmd/run.js
- src/cmd/transpile.js
- xtask/src/build/jco.rs
- xtask/src/generate/tests.rs
- xtask/src/main.rs
- xtask/src/test.rs
Optimizes the GitHub actions workflow a bit - separates steps for the build and WASI conformance test generation, caching the artifacts, then separating the matrix test runs from these generations.
Also adds binaryen optimizations to the release builds.
> GitHub actions workflow optimization

- crates/js-component-bindgen/src/intrinsics.rs
This adds support for uninitialized resource table transfer. In rare edge cases where the target table is not otherwise referenced by any bindgen code and the resource is never dropped, it is possible for the target table in transfer to not otherwise be initialized by the component bindgen.
I don't want to land this without creating a simple test, and fully understanding what mechanisms can lead to this though, because it seems very odd to have an undroppable resource.
> fix: support uninitialized resource transfer

- crates/js-component-bindgen/src/transpile_bindgen.rs
- crates/js-component-bindgen/src/ts_bindgen.rs
- test/eslintrc.cjs
Based on discussion in https://github.com/bytecodealliance/jco/issues/375.
> Generator-based initialization function

- package.json
- src/browser.js
Resolves https://github.com/bytecodealliance/jco/issues/464.
> fix: support browser types to match component typing

- src/browser.js
Fixes the browser entrypoint change from https://github.com/bytecodealliance/jco/pull/465.
> fix: variable deduping in browser entrypoint

- src/cmd/run.js
> fix: path to preview2-shim for run

- crates/js-component-bindgen/src/function_bindgen.rs
Resolves https://github.com/bytecodealliance/jco/issues/484 where `postReturn` can be called before retrieving data.
> fix: call post-return after building return value

- examples/components/string-reverse-upper/README.md
Thanks to @chrisobdam for finding this!
> fix(examples): mention wac in string-reverse-upper README

- package-lock.json
- package.json
Includes the fixes for supporting top-level resources.
> deps: update to ComponentizeJS@0.15.0

- package-lock.json
- package.json
- test/fixtures/componentize/wasi-http-proxy/source.js
- test/preview2.js
Relands the ComponentizeJS test to the latest ComponentizeJS 0.16.0 on WASI@0.2.3.
> test: latest ComponentizeJS test

- src/cmd/run.js
Resolves https://github.com/bytecodealliance/jco/issues/570.
> fix: jco serve --port handler

- crates/js-component-bindgen/src/transpile_bindgen.rs
This resolves https://github.com/bytecodealliance/jco/issues/567, which was a regression caused in https://github.com/bytecodealliance/jco/pull/519 where the initializer style trampolines (`const trampoline{} = ...`) being output late caused them not to be defined in usages when using the `instantiation` flag option.
The simple approach here is to segment trampolines into those that need late resource information only available after all imports and exports bindgen, which are functions that can be hoisted, and those that are const initializers but don't need the late post-bindgen binding information.
> fix: trampoline initialization ordering

- crates/js-component-bindgen/src/intrinsics.rs
This commit enables objects to be set on the global context and used via the WebIDL integration in Jco. Previously, objects would be detected as functions and then proxied into another function, which prevented Object.create(O.prototype) calls from succeeding.
With this change, we do a little more work to check for check for dealing wiht a class.
> fix: allow objects through globalThis intrinsic (WebIDL)

- crates/js-component-bindgen-component/src/lib.rs
- crates/js-component-bindgen/src/lib.rs
- src/cmd/transpile.js
- test/fixtures/wits/invalid/invalid-fn.wit
- test/fixtures/wits/invalid/sibling-diff-pkg/component.wit
- test/fixtures/wits/invalid/sibling-diff-pkg/interface.wit
- test/fixtures/wits/invalid/sibling-diff-pkg/no-deps/component.wit
- test/fixtures/wits/invalid/sibling-diff-pkg/no-deps/interface.wit
- test/fixtures/wits/valid/no-deps/component.wit
- test/fixtures/wits/valid/no-deps/interface.wit
- test/wit.js
- xtask/src/generate/wasi_types.rs
This commit adds a hint and some extra context for errors related to type generation, along with some regression tests to ensure we're displaying useful hints
Resolves #442 
**Also, don't worry, I fixed "in correctly"**
> feat: improve error message for invalid hint

- xtask/src/generate/preview2_tests.rs
This commit allow for a retry mechanism on tests that are known to be flaky that do network access.
> refactor(tests): allow for retries on known flaky network tests

- .github/workflows/create-release-pr.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
- .github/workflows/tag-release.yml
- cliff.toml
- crates/js-component-bindgen/cliff.toml
- packages/preview2-shim/cliff.toml
This PR adds an automated release workflow to jco to make creating release PRs, tagging releases, and publishing artifacts a bit easier.
While we can't have the flow be completely automated (credentials & PATs aren't attached to the repo), but generally by kicking off the given action flows (`create-release-pr` -> `tag-release` -> `release`), the release process can be automated (and lead to a manual release by a maintainer).
> feat(ci): add release PR creation workflow

- src/cmd/componentize.js
- src/jco.js
using the flag `--debug-starlingmonkey-build`
> expose comoponentizejs's debugBuild option on command line

- packages/preview3-shim/lib/nodejs/clocks.js
- packages/preview3-shim/lib/nodejs/index.js
- packages/preview3-shim/test/clocks.test.js
Split from: https://github.com/bytecodealliance/jco/pull/653
> feat(p3-shim): implement wasi preview3 clocks API

- packages/preview3-shim/lib/nodejs/index.js
- packages/preview3-shim/lib/nodejs/random.js
Split from: https://github.com/bytecodealliance/jco/pull/653
> feat(p3-shim): implement wasi preview3 random API

- packages/preview3-shim/lib/nodejs/filesystem/descriptor.js
Lazily create a worker for the descriptor.
> fix(p3-shim): avoid side effects when loading filesystem API

- packages/preview3-shim/lib/nodejs/cli.js
- packages/preview3-shim/lib/nodejs/index.js
- packages/preview3-shim/lib/nodejs/workers/cli-worker.js
- packages/preview3-shim/test/cli.test.js
Split from: https://github.com/bytecodealliance/jco/pull/653
This is API is subject to change (see https://github.com/WebAssembly/wasi-cli/issues/65) but for now is consistent with implementation from https://github.com/bytecodealliance/wasip3-prototyping
> feat(p3-shim): implement wasi preview3 cli API

- crates/js-component-bindgen/src/intrinsics.rs
- crates/js-component-bindgen/src/transpile_bindgen.rs
This commit implements task.cancel rudimentarily, but without tests. Tests for task.cancel will have to wait until subtask.cancel is implemented along with more of the async machinery
> feat(bindgen): implement task.cancel

- crates/js-component-bindgen/src/intrinsics/component.rs
> fix(jco): const reassignment of variable in component async state

- crates/js-component-bindgen/src/function_bindgen.rs
> fix(jco): use unsigned int for pointer load sizing
