bytecodealliance/jco

src/common.js
src/jsct.js

This should fix Windows support for JSCT, resolving https://github.com/bytecodealliance/js-component-tools/issues/4.

fix: windows support

---

src/cmd/opt.js

This fixes Wasm-opt options, ensuring that `--enable-bulk-memory` is on by default and that custom opt args are properly passed through.
Resolves https://github.com/bytecodealliance/js-component-tools/issues/9.

fix: wasm-opt options

---

Cargo.lock
Cargo.toml
README.md
api.d.ts
crates/wasm-tools-component/Cargo.toml
crates/wasm-tools-component/src/lib.rs
crates/wasm-tools-component/wit/wasm-tools.wit
src/api.js
src/cmd/opt.js
src/cmd/transpile.js
src/cmd/wasm-tools.js
src/common.js
src/jsct.js
test/api.js
test/cli.js

This adds support for the `wasm-tools component embed` command which is the new way to embed world information into component binaries now that it has been separated from the `wasm-tools component new` command.
This enables the former component new use cases within the JS toolchain and also updates Cargo dependencies.

feat: wasm-tools component embed support

---

crates/js-component-bindgen-component/Cargo.toml
crates/js-component-bindgen-component/src/lib.rs
crates/js-component-bindgen/Cargo.toml
crates/js-component-bindgen/src/bindgen.rs
test/cli.js

This adds a new `raw_bindgen` generation option, along with flattening the generation output so that import functions are declared flat as opposed to within the initialization closure.
This option disables the imports, exports and initialization, effectively exposing a contract of:
* Imports must define functions `lowering{idx}Callee`
* Lowered imports can be referenced via `lowering{idx}`
* `memory{idx}`, `realloc{idx}`, `exports{idx}` are defined variables, but must be set externally
* Exported interfaces are provided by their exact names
Intrinsics are still output exactly, modular / separated intrinsics could be further looked into as a possible future feature.
The above bindgen with some well-defined wrapping enables more flexible embedding scenarios. I think this embedding use case …

feat: raw bindgen option for custom wrapping

---

Cargo.lock
Cargo.toml
README.md
api.d.ts
crates/wasm-tools-component/Cargo.toml
crates/wasm-tools-component/src/lib.rs
crates/wasm-tools-component/wit/wasm-tools.wit
src/api.js
src/cmd/wasm-tools.js
src/jsct.js
test/api.js
test/cli.js

This adds the `jsct metadata` command from Wasm Tools as `wasm-tools metadata show`.
In addition `metadata` can be provided to the `embed` command and API so that when creating a component via a `new + embed` workflow, the producer metadata can be provided that way.
My tendency was not to provide the "add metadata" function since this is more designed to be a tool for consuming components than creating them, so specifically only targeting the `embed` workflow seems like it fulfills the major requirements of a standard component creation process embedding metadata such as is used in js-compute-runtime.
The embedding option didn't seem to pass through the metadata on its own so I had to add an additional write to this. Unsupported fields throw in the embedding process.

feat: producer metadata tooling

---

crates/js-component-bindgen/src/bindgen.rs
test/api.js

Adds support for wildcard mappings, as described in https://github.com/bytecodealliance/js-component-tools/issues/13.

feat: wildcard maps

---

.gitignore
EXAMPLE.md
README.md
build-dist.sh
package.dist.json
package.json
src/jco.js
test/cli.js
test/codegen.js
test/helpers.js

This renames the project to "jco", with both the project name, CLI and library being under this single name. This would then be published as `@bytecodealliance/jco` on npm.
Will leave this open for now for feedback, but the plan will be to release with this renaming along with the latest changes in the next couple of days.

Rename to jco

---

packages/preview2-shim/lib/nodejs/http.js

This treats `synckit` used in the Node.js http shim as an optional dependency.
@eduardomourar ideally I think we should fully inline any dependency usage if we can, as it would be great to have no dependencies for this.

fix: treat synckit as an optional dependency

---

Cargo.lock
Cargo.toml
README.md
crates/wasm-tools-component/src/lib.rs
crates/wasm-tools-component/wit/wasm-tools.wit
src/cmd/opt.js
test/api.js
test/cli.js

Updates `wasm_metadata` to main which includes a bug fix for a bug in the `0.2.0` version on crates.io.
This also includes ranges now, so we no longer need a custom extract core modules function as well.

deps: wasm_metadata update

---

README.md
build-dist.sh
package.json
src/api.js
src/cmd/componentize.js
src/cmd/opt.js
src/jco.js
test/cli.js
test/fixtures/source.js
test/fixtures/source.wit

This adds a `jco componentize source.js -w world.wit -o component.wasm` command to `jco` as a wrapper around `ComponentizeJS`.
We could support alternative componentization projects in this CLI work, via an `--engine` field as appropriate, so this doesn't necessarily tie us to this specific approach entirely, but instead an overall toolchain contract for now.

feat: componentize command

---

crates/js-component-bindgen/src/bindgen.rs

The following types were not being added to generated type definition: `Option<T>` and `Result<T, E>`.

fix: post types is being skipped

---

README.md
package.json
src/api.js
src/cmd/componentize.js

This removes `@bytecodealliance/componentize-js` as a static dependency and instead requires it to be separately installed.
This way, we don't have a circular dependency between the packages, and also this allows a nicer path for multi-engine support.

feat: explicit componentize install

---

packages/preview2-shim/lib/http/wasi-http.js

Because the options parameter passed to the handle method can be `null`, we need to deconstruct it in a safer manner (or just leave that for later) in order to avoid error such as:
> TypeError: Cannot read properties of null (reading 'connectTimeoutMs')

fix: http handle options can be null

---

crates/js-component-bindgen/src/esm_bindgen.rs
crates/js-component-bindgen/src/transpile_bindgen.rs
src/cmd/transpile.js

Adds missing WASI mappings when using the wasi shim default mappings to the preview2 shims package.

fix: missing wasi-shim mappings

---

package.json
src/cmd/opt.js
src/cmd/transpile.js
src/ora-shim.js

Adds a shim for `ora` in the browser towards supporting jco in the browser.

feat: ora browser shim

---

package.json
test/cli.js

Reenables the componentize test that was disabled during the recent WIT upgrades. This doesn't affect the release as it is already supported.

test: reenable componentize test

---

crates/js-component-bindgen/src/esm_bindgen.rs
test/fixtures/component-gen/import-fn.js
test/fixtures/component-gen/import-fn.wit
test/runtime/import-fn.ts
update-tests.sh

Resolves the JS output case described in https://github.com/bytecodealliance/jco/issues/103.
When using `--instantiation`, with kebab function imports of a world of the form `import x: func () -> ()`, instead of outputting:
```js
const x = imports.x.default;
```
we were outputting:
```js
const x = imports.default;
```

fix: default import function instantiation

---

src/cmd/transpile.js

This always adds `--no-wasi-shim` when in instantiation mode.
This should avoid issues like https://github.com/tc39/proposal-import-attributes/issues/145, until we properly support TypeScript generation for map configuration.

fix: disable wasiShim for instantiation

---

crates/js-component-bindgen/src/ts_bindgen.rs

I'm assuming the `drop` call was to get rid of the "unused" warning, but this just generates "dropping references does nothing" warning instead.

Fix "dropping reference" warning

---

Cargo.lock
crates/js-component-bindgen/src/esm_bindgen.rs
crates/js-component-bindgen/src/ts_bindgen.rs

This fixes https://github.com/bytecodealliance/jco/issues/112 ensuring cross-interface TS references use the correct naming conventions for interfaces.
Instead of separate `imports` and `exports`, we now have a single `interfaces` folder, and ensure all typing use the same naming conventions.

fix: cross-interface TS references

---

packages/preview2-shim/lib/browser/clocks.js

performance.now() returns milliseconds, and we want nanoseconds, so we need to multiply by a million, not a billion.
Using one `Date.now()` prevents a "bad" case when one first Date.now() call returns a different date than the second Date.now() call, which can be especially bad if the two dates "cross over" the millisecond boundary.

Update js wasi clocks

---

crates/js-component-bindgen/src/function_bindgen.rs
crates/js-component-bindgen/src/transpile_bindgen.rs

This avoids forcing a transitive wastime-environ dependency on consumers of the API.

deps: use wit-component string encoding for public interface

---

crates/js-component-bindgen/src/transpile_bindgen.rs
package.json
src/cmd/componentize.js
src/jco.js
test/cli.js

This upgrades `jco componentize` to the latest ComponentizeJS build, which now removes WASI imports by default so that we are back to having simple components. Stdout can be enabled for console logging via `jco componentize --enable-stdout` which will then include the WASI interfaces again.

fix: jco componentize for latest ComponentizeJS

---

Cargo.lock
Cargo.toml
crates/js-component-bindgen/src/transpile_bindgen.rs

This commit updates the Wasmtime dependency to the, currently unreleased, Wasmtime 12.0.0 branch. A number of changes happened to component translation in Wasmtime 12 to account for resources which required changes here as well. Additionally Wasmtime 12 disallows empty types in components which WASI was previously using, so this additionally updates the preview1 shims and test components.

Update to Wasmtime 12

---

Cargo.lock
Cargo.toml
crates/js-component-bindgen-component/Cargo.toml
crates/js-component-bindgen-component/src/lib.rs
crates/js-component-bindgen/Cargo.toml
crates/js-component-bindgen/src/core.rs
crates/js-component-bindgen/src/lib.rs
crates/js-component-bindgen/src/transpile_bindgen.rs
test/codegen.js
test/fixtures/components/list-adapter-fusion.wat
test/runtime.js
test/runtime/list-adapter-fusion.ts

Currently JS does not generally support the WebAssembly multi-memory
proposal. Wasmtime will, however, generate adapter modules which use
multi-memory to communicate between components. This means that composed
components are typically not compatible with the transpile process as
they produce a core module that doesn't actually run in any JS runtime.
This commit fixes this issue by adding polyfill support for
multi-memory. Whenever an adapter is produced that uses multi-memory jco
will now rewrite the module such that any references to memory that
isn't at index 0 to be indirected through functions. These imported
functions then operate on the specified memory on behalf of the wasm
itself. This is a horribly slow process because all memory reads/writes
become function calls, but given …

 Support polyfilling multi-memory 

---

crates/js-component-bindgen/src/function_bindgen.rs

WIT component now has the ability to support arbitrary post calls and not just post calls when there is allocation to be freed.
This updates the post call output to not assume a `ret` parameter in those cases.

feat: allow arbitrary post calls

---

src/cmd/wasm-tools.js
src/jco.js
test/cli.js

Running `jco new app.wasm -o app.component.wasm --adapt wasi_snapshot_preview1=lib/wasi_snapshot_preview1.reactor.wasm` etc is such a mouthful to type.
This adds a new `jco new app.wasm --wasi-comand -o app.command-component.wasm` to make it easier to create components in one liners (and for `--wasi-reactor`). Easy to do in jco since we already host the adapters.

feat: --wasi-command / --wasi-reactor flags for component new

---

package.json
src/browser.js
test/browser.html

Adds a simple browser build test and exposes it for library use.
Resolves https://github.com/bytecodealliance/jco/issues/42.

feat: simple browser build

---

crates/js-component-bindgen/src/function_bindgen.rs

Fixes a bug where local component resources handles are already handles so don't need to be re-registered.

fix: local resources handle refs

---

src/cmd/wasm-tools.js

This fixes a bug with the `componentNew` implementation where passing an adapter without using one of the new `--wasi-reactor` or `--wasi-command` flags would bail on a null property access.

fix: component new adapter null bug

---

packages/preview2-shim/package.json

This removes the `"engines"` field from the preview2-shim package.json, which unnecessarily restricts usage of the package.

fix: remove engines field restriction in preview2-shim

---

package.json
src/cmd/componentize.js
src/jco.js

Adds a new `--preview2-adapter` for customizing the adapter when running ComponentizeJS. This is useful when using different WIT versions than the JCO release version.

feat: --preview2-adapter option for componentizeJS

---

crates/js-component-bindgen-component/Cargo.toml
crates/js-component-bindgen/Cargo.toml

For some reason my local workspace was giving errors for the dot notation in toml; this fixes that by using toml maps instead. Thanks!

fix toml errors in editor

---

packages/preview2-shim/lib/nodejs/filesystem.js
xtask/src/build.rs

This fixes a bug that was only reproducing locally where the xtask copy would delete the contents of the source file.
I initially thought this was due to the new filesystem work, so did a bunch of refactoring on edge cases of the implementation I could find, as a result the filesystem support in Node.js is now better and I actually did fix a bunch of bugs there even though we weren't hitting them :)

fix: xtask weirdness

---

crates/js-component-bindgen/src/function_bindgen.rs
crates/js-component-bindgen/src/transpile_bindgen.rs
test/codegen.js
test/fixtures/wits/resource-naming.wit
test/fixtures/wits/resource-naming/resource-naming.wit

Fixes resource deduping when imported and exported resources have the same name.

fix: resource deduping

---

xtask/src/build.rs

Per https://github.com/bytecodealliance/jco/issues/188, this turned out to be a `node_modules` vestige.

fix: reenable xtask copy

---

crates/js-component-bindgen/src/function_bindgen.rs

This removes an unused variable from `function_bindgen.js`; I think this must have been left behind during a recent refactor.

Fix 'unused variable' warning

---

.github/workflows/docs.yml

mdbook wasn't deploying because the main branch is called `main`, not `master`.

point mdbook deploy to main

---

Cargo.lock
Cargo.toml
crates/js-component-bindgen/src/function_bindgen.rs
crates/js-component-bindgen/src/lib.rs
crates/js-component-bindgen/src/transpile_bindgen.rs
test/api.js
test/cli.js
test/fixtures/components/list-adapter-fusion.wat

This is to support resource handle lifting and lowering from the guest's point-of-view.  Unlike with the other, structural data types, resource bindings must be either host- or guest-specific (i.e. the bindings are not symmetric).
I'll follow this up with a `componentize-js` PR that includes a bunch of tests.
Note that I had to update several dependencies to pull in https://github.com/bytecodealliance/wasm-tools/pull/1218, which addresses the case of a WIT world that `use`s a resource from an interface while also exporting the interface.

resource support for `componentize-js`

---

crates/js-component-bindgen/src/esm_bindgen.rs
crates/js-component-bindgen/src/function_bindgen.rs
crates/js-component-bindgen/src/transpile_bindgen.rs

This fixes a remaining bug with connecting resources.
Basically, the current `connect_resources` implementation only walks the resources references by the current function. So when you have a resource that only has a static function that doesn't take a resource as an argument you never actually end up connecting that resource. Instead this moves the entire connect resources phase to a phase before initialization.
Thanks to @alexcrichton for helping me work through this case.

fix: resource connections

---

crates/js-component-bindgen/src/transpile_bindgen.rs

This fixes a bug with resource aliasing where exported functions should reference from the imported resource map.

fix: resource aliasing

---

crates/js-component-bindgen/src/ts_bindgen.rs

Adding the file extension will allow the interface imports to work for typescript packages using both `moduleResolution` `bundler` as well as `nodenext`. This is also more closely aligned with the node spec for imports so should be better supported. Closes #223

Adding file extension to interface imports

---

src/cmd/run.js

`src/cmd/run.js` is poorly structured. In particular:
* `await rm(outDir, ...)` appears in two places, neither of which will be reached if the `spawn()` call is successful but the `ChildProcess` then emits an `error` event.
* If it is unable to locate the `@bytecodealliance/preview2-shim` package, it simply returns without setting a non-zero exit code (fixed here by setting the exit code to `1`).
This pull request fixes all this. It also fixes #180.

Refactor `src/cmd/run.js`

---

package.json
test/fixtures/componentize/wasi-http-proxy/source.js
test/runtime/wasi-http-proxy.ts

Thanks to the fix by @dicej, this gets headers working for `wasi-http` reenabling the previous tests.

fix: http headers support

---

crates/js-component-bindgen/src/ts_bindgen.rs
test/tsconfig.json

While testing `0.13.2` earlier today I realized that my change in #228 missed a case. While it covered type imports it missed importing functions in `.d.ts` files. This change fixes that and also updates the `moduleResolution` field in the test tsconfig to `nodenext` since the ts docs state: 
>"You probably won’t need to use `node10` (equivalent to `node`) in modern code." 
This means that the existing `Verify Typescript output` test now implicitly tests for the presence of the `.js` extensions because it would fail to compile without them. 
See ts docs for more info on the `nodenext` module resolution strategy and the deprecation of `node`:
https://www.typescriptlang.org/tsconfig#moduleResolution

Adding `.js` file extension to function type imports

---

crates/js-component-bindgen/src/function_bindgen.rs
crates/js-component-bindgen/src/intrinsics.rs
crates/js-component-bindgen/src/transpile_bindgen.rs
packages/preview2-shim/lib/common/io.js
packages/preview2-shim/lib/nodejs/cli.js
packages/preview2-shim/lib/nodejs/filesystem.js
packages/preview2-shim/lib/nodejs/http.js
packages/preview2-shim/test/test.js
test/helpers.js

This implements `Symbol.dispose` support as described in https://github.com/bytecodealliance/jco/issues/236.
The major feature enabled by this is the ability to use `Symbol.dispose` to define explicit deconstructors for JS classes that are imported by Wasm.
In addition, `Symbol.dispose` can be used to also eagerly drop own resources, which will cause handles to be immediately invalidated as if there was an explicit drop, as opposed to a GC based drop.

feat: Symbol.dispose own-handle destructors

---

crates/js-component-bindgen/src/function_bindgen.rs

Fixes a bug where the symbol dispose function was not applying the descriptor call property including not setting the value as writable. I believe this was the root cause of the bug that prompted https://github.com/bytecodealliance/jco/pull/242 @dicej.

fix: dispose definition value

---

README.md
crates/js-component-bindgen-component/src/lib.rs
crates/js-component-bindgen-component/wit/js-component-bindgen.wit
crates/js-component-bindgen/src/function_bindgen.rs
crates/js-component-bindgen/src/intrinsics.rs
crates/js-component-bindgen/src/lib.rs
crates/js-component-bindgen/src/transpile_bindgen.rs
crates/js-component-bindgen/src/ts_bindgen.rs
src/cmd/transpile.js
src/jco.js
test/browser.html
test/codegen.js
test/runtime/helpers.ts
test/runtime/strings.sync.ts
test/test.js
xtask/src/build/jco.rs
xtask/src/generate/wasi_types.rs

This code should ideally be reviewed patch by patch.
The idea is to implement the feature described in https://github.com/bytecodealliance/jco/issues/245.
First off, this patch updates the `--instantiation` option to receive a string value instead of a being a switch. The possible values are `async` (the default) or `sync`. The fact that `async` is the default value ensures the backward compatibility.
Next, this patch updates the `TranspileOpts::instantiation` field to be `Option<InstantiationMode>` instead of `bool`. `InstantiationMode` is a enum with 2 variants: `Async` and `Sync`. The code is updated accordingly.
Next, the same patch adds non-async code during the bindgen pass.
The next patches are about improving the test framework, and adds a new test case for non-async generated …

feat: Allow `--instantiation` to generate non-async code

---

README.md
docs/src/contributing.md
docs/src/example.md
packages/preview2-shim/README.md

Updates the readmes for the latest status and improves the contribution guide.
This should resolve https://github.com/bytecodealliance/jco/issues/62 and https://github.com/bytecodealliance/jco/issues/184.

doc: update readmes, better contribution guidelines

---

packages/preview2-shim/lib/io/worker-io.js
packages/preview2-shim/lib/io/worker-thread.js
packages/preview2-shim/lib/nodejs/cli.js
packages/preview2-shim/lib/nodejs/filesystem.js
packages/preview2-shim/lib/nodejs/http.js
packages/preview2-shim/test/test.js

Node.js doesn't provide the ability for blocking stdio on the worker thread, so we get no benefits handling it off thread, at the same time we don't get proper flush behaviours from the worker stdout so moving it to the main thread ensures that we get synchronous flushing most of the time.

fix: move stdio to main thread

---

packages/preview2-shim/lib/io/worker-thread.js
packages/preview2-shim/lib/nodejs/cli.js

This enables stdio in the thread in addition to the main thread stdio.
This way operations like splicing for stdio can still happen in the thread, while normal write operations short-circuit in the main thread for the better blocking behaviours.

fix: stdio thread in addition to main thread

---

tests/virtualenvs/base.js

There was a missing OS separator `sep` in this line that failing with an `EACCESS` error when running tests on WSL:
https://github.com/bytecodealliance/jco/blob/df1f3005cfcb3ea9fb7c89b8e756c18c53b65abc/tests/virtualenvs/base.js#L8

fix(tests): fix eacces in WSL when creating virtualenvs

---

src/cmd/transpile.js

The API documentation of `transpileComponent` was incorrect, leading to false-negative warnings in the code when an appropriated IDE is used.
This patch corrects the API documentation.

doc: Fix API documentation of `transpileComponent`

---

crates/js-component-bindgen/src/intrinsics.rs
src/cmd/transpile.js
test/cli.js
test/runtime/strings.async+js.ts
test/runtime/strings.sync+js.ts

This patch aims at supporting `--js` with `--instantiation`.
`--js` needs an `instantiate` function to work, so it might look like
`--instantiation` is always implied, but actually no. It is correct
that when `--js` is present, an `instantiate` function _is_ generated,
but it doesn't mean that we expect the function to be used, it's simply
not exported, plus `instantiate` is automatically called (if `--tla-compat`
is `false`). When `--instantiation` is missing, functions are exported
with the `export` directive, and imports are imported with the `import`
directive. When `--instantiation` is present, there is no `export` and no
`import`: only a single exported `instantiate` function.
Basically, we get this:
* `--js` only:
* `instantiate` is renamed to `_instantiate`,
* A new `instantiate` …

Use `--js` with `--instantiation`

---

src/cmd/transpile.js

Fixes a bug from the `--no-namespaced-exports` flag disabling namespaced exports by default.

fix: --no-namespaced-exports parity

---

packages/preview2-shim/lib/browser/http.js
src/browser.js
src/cmd/transpile.js
test/browser.html

Fixes the browser build and makes it async by default to support TLA compat, resolving https://github.com/bytecodealliance/jco/issues/284 and https://github.com/bytecodealliance/jco/issues/285.

fix: browser build, with tla compat

---

Cargo.toml
package.json
xtask/src/build/jco.rs
xtask/src/build/workspace.rs
xtask/src/main.rs

Adds a new `npm run build:release` with release build optimizations applied.
Resolves https://github.com/bytecodealliance/jco/issues/286.

perf: add release profile optimizations, separate release build

---

packages/preview2-shim/lib/io/worker-thread.js
packages/preview2-shim/lib/nodejs/sockets.js
packages/preview2-shim/lib/nodejs/sockets/tcp-socket-impl.js
packages/preview2-shim/lib/nodejs/sockets/udp-socket-impl.js
packages/preview2-shim/lib/nodejs/sockets/wasi-sockets.js
tests/generated/cli_no_ip_name_lookup.rs
tests/generated/cli_no_tcp.rs
tests/generated/cli_no_udp.rs
tests/virtualenvs/deny-dns.js
tests/virtualenvs/deny-tcp.js
tests/virtualenvs/deny-udp.js
xtask/src/generate/tests.rs

Adds support for denying dns lookups, tcp and udp.

feat: sockets deny functionality

---

crates/js-component-bindgen/src/transpile_bindgen.rs
packages/preview2-shim/lib/io/worker-io.js
packages/preview2-shim/lib/io/worker-thread.js

This gets the tests up to 89/100 passing fixing the stdin splice test along with a bindgen issue for multi-version bindgen and a fix for poll-list's implementation.

fix: stdin splice

---

.github/workflows/main.yml
packages/preview2-shim/lib/io/worker-http.js
packages/preview2-shim/lib/io/worker-thread.js
packages/preview2-shim/lib/nodejs/http.js

This updates the agent support to use a dedicated HTTP agent, resolving the compat issue on Node.js 18, where keepalive as the default changed.
This also implements the connection timeouts feature for HTTP and adds the Node.js 18 and latest CIs to the matrix.
Resolves https://github.com/bytecodealliance/jco/issues/311.

fix: HTTP agent support, timeouts

---

packages/preview2-shim/lib/nodejs/http.js

This fixes the trailers handling, which is the only HTTP feature we don't yet support.
For now we:
1. Always return `undefined` when checking for trailers
2. Throw an internal error `"trailers unsupported"` when trying to set trailers

fix: trailers unsupported errors

---

packages/preview2-shim/lib/io/worker-socket-tcp.js
packages/preview2-shim/lib/io/worker-thread.js
packages/preview2-shim/lib/nodejs/sockets/tcp-socket-impl.js

Both `preview2_tcp_states `and `preview2_tcp_sockopts` are passing.
Related https://github.com/bytecodealliance/jco/issues/315

chore: preview2_tcp_sockopts passing

---

packages/preview2-shim/lib/io/worker-io.js
packages/preview2-shim/lib/io/worker-thread.js
packages/preview2-shim/lib/nodejs/filesystem.js
tests/generated/api_read_only.rs
tests/generated/preview1_path_open_read_write.rs
tests/generated/preview2_tcp_sample_application.rs
tests/virtualenvs/readonly.js
xtask/src/generate/tests.rs

This fixes the remaining WASI filesystem tests, which means we're now at 100% conformance, down to sockets support.
Resolves https://github.com/bytecodealliance/jco/issues/203.

fix: wasi filesystem tests

---

crates/js-component-bindgen/src/names.rs
crates/js-component-bindgen/src/transpile_bindgen.rs
test/fixtures/wit/wasi-http.wit

Fixes https://github.com/bytecodealliance/jco/issues/331, supporting JS reserved words in resource method names.

fix: support for js reserved words in resource method names

---

test/api.js

Test `map` when mapping with both wildcards and into package import specifiers.

test: wildcard imports

---

packages/preview2-shim/lib/io/worker-thread.js
tests/generated/mod.rs
tests/generated/proxy_echo.rs
tests/generated/proxy_handler.rs
tests/generated/proxy_hash.rs
xtask/src/generate/tests.rs

This fixes the the remaining failures on the HTTP conformance tests from the latest refactoring in https://github.com/bytecodealliance/jco/pull/334.

fix: http conformance tests

---

packages/preview2-shim/lib/io/calls.js
packages/preview2-shim/lib/io/worker-socket-tcp.js
packages/preview2-shim/lib/io/worker-thread.js
packages/preview2-shim/lib/nodejs/http.js
packages/preview2-shim/lib/nodejs/sockets.js
packages/preview2-shim/test/test.js

This fixes the TCP state implementation to now provide spec-correct state transitions as defined in https://github.com/WebAssembly/wasi-sockets/blob/99325cff6762ebe06693e56b408b44b463895c97/TcpSocketOperationalSemantics.md, including supporting the pollable multi-state transitions as implemented on top of https://github.com/bytecodealliance/jco/pull/334.
This completes the TCP implementation.

wasi: correct tcp state implementation

---

packages/preview2-shim/lib/io/calls.js
packages/preview2-shim/lib/io/worker-http.js
packages/preview2-shim/lib/io/worker-io.js
packages/preview2-shim/lib/io/worker-socket-tcp.js
packages/preview2-shim/lib/io/worker-thread.js
packages/preview2-shim/lib/nodejs/clocks.js
packages/preview2-shim/lib/nodejs/filesystem.js
packages/preview2-shim/lib/nodejs/http.js
packages/preview2-shim/lib/nodejs/sockets.js
packages/preview2-shim/package.json
packages/preview2-shim/test/test.js

This resolves the GC integration for the JS preview2-shims bindings, where if a `Symbol.dispose` call is not done for any resource, the GC will always kick in and handle the resource finalization in this case.
This is typically only for invalid components, but also affects direct usage of the preview2 APIs from JS where manual `Symbol.dispose` calls are forgotten to be called by a consumer.
One complexity here is that when the GC runs, it can dispose parent resources before their children. To avoid this, we create a strong reference in the finalizer for any child resource to its parent resource, so that this is not possible by the semantics of the GC itself. Thanks to @alexcrichton for suggesting the approach to this problem here. GC tests are included in the preview2 unit tests using the …

feat: GC finalization for preview2-shims

---

crates/js-component-bindgen/src/function_bindgen.rs
test/cli.js
test/fixtures/componentize/source.js
test/fixtures/componentize/source.wit

Fixes https://github.com/bytecodealliance/jco/issues/337 as described in https://github.com/bytecodealliance/jco/issues/337#issuecomment-1894471068 where own resources passed back into components defining those resources are still fully maintained in the handle table.

fix: own resource handle rep

---

.github/workflows/main.yml
crates/js-component-bindgen-component/src/lib.rs
crates/js-component-bindgen-component/wit/js-component-bindgen.wit
crates/js-component-bindgen/src/core.rs
crates/js-component-bindgen/src/lib.rs
crates/js-component-bindgen/src/transpile_bindgen.rs
package.json
src/cmd/transpile.js
src/jco.js
test/api.js
test/cli.js
test/helpers.js
xtask/src/build/jco.rs
xtask/src/generate/wasi_types.rs

Adds a `--multi-memory` flag to JCO transpile to disable the multi memory polyfill.
Resolves https://github.com/bytecodealliance/jco/issues/356.

feat: add --multi-memory flag

---

crates/js-component-bindgen/src/transpile_bindgen.rs

The current default parameter does not work. When running the generated code one gets:
```
new WebAssembly.Instance,
^
TypeError: WebAssembly.Instance(): Argument 0 must be a WebAssembly.Module
```

fix: generated default arg WebAssembly.Instance needs to be called as constructor

---

crates/js-component-bindgen/src/transpile_bindgen.rs
crates/js-component-bindgen/src/ts_bindgen.rs

Fix support for `--tla-compat` combined with `--instantiation`.
Resolves https://github.com/bytecodealliance/jco/issues/367.

fix: tla-compat for instantiation

---

Cargo.lock
Cargo.toml
crates/js-component-bindgen-component/src/lib.rs
crates/js-component-bindgen/src/core.rs
crates/js-component-bindgen/src/lib.rs
crates/js-component-bindgen/src/transpile_bindgen.rs
test/api.js
test/cli.js

There have been breaking change added to wasmtime that jco hasn't started using yet.  This PR does the bare minimum needed to update and preserve prior functionality.  The two nontrivial updates that were added were
1.) GC instructions added to wasm-tools
2.) Support for introspection in wasmtime
For both of these, I did the simplest thing I could, frequently leaving things unimplemented, but figured that may be fine given other parts of the code.
Below are notes on how the PR currently deals with each of the needed updates
1.) Takes inspiration from similar macro blocks in `wasm-tools`, and occasionally relies on an unimplemented method on `Translator` trait.  Some of the inspiration came from `wasm-mutate`, but there are similar macro rules in `wit-component` in the gc module.  I'm not …

deps: upgrade to wasmtime@18.0.0 toolchain

---

crates/js-component-bindgen/src/function_bindgen.rs

This adds a fix to ComponentizeJS resource generation to handle the resource change from https://github.com/bytecodealliance/jco/pull/361 and exactly as its converse.

fix: componentize-js resource generation

---

README.md
docs/src/example.md
docs/src/transpiling.md

This makes the existing example use ComponentizeJS to create the demo component so that it is a fully runnable end to end example.
Resolves #278.

docs: fix end-to-end example

---

src/cmd/componentize.js

Fixes `jco componentize` to provide the `sourceName` for use in ComponentizeJS error messages.

fix: pass sourceName to componentizeJS

---

packages/preview2-shim/lib/io/worker-io.js
packages/preview2-shim/lib/io/worker-socket-tcp.js
packages/preview2-shim/lib/io/worker-thread.js
packages/preview2-shim/lib/nodejs/filesystem.js
packages/preview2-shim/lib/nodejs/http.js
packages/preview2-shim/lib/synckit/index.js

Just a first draft PR to feed the CI pipeline, because local testing doesn't work on my machine.
Fixes: #385
Warning! -- there are important parts missing/untested!
* `validateHeaderName` and `validateHeaderValue` are temporary replaced by dummy entries.
This should be better fixed on the `deno` side (see: https://github.com/denoland/deno/issues/22614).
* The `worker_thread.unref()` case is still uttery unsolved and just temporary removed.

fixes for `deno` compatibility

---

crates/js-component-bindgen/src/function_bindgen.rs
crates/js-component-bindgen/src/intrinsics.rs
crates/js-component-bindgen/src/transpile_bindgen.rs

This updates the resource tables to use a fixed sized array of numbers with a free list as a slab implementation for more optimal resource operations.
The table data structure is also designed to be used in the new low-level bindgen for optimized table operations..
Previously, we were using a non-numeric `rep` for imported resources, where instead of using a number we would just reference the JS class instance directly in this position. Now that `rep` is only numeric, this also implements a separate `captureTable` to do rep assignment for captured imported resources, while retaining the same semantics.

feat: slab implementation for resource tables

---

packages/preview2-shim/lib/nodejs/http.js

See #394 for a more detailed discussion. 
In short the current implementation of `wasi:http` `RequestOptions` incorrectly handles nano/milliseconds and it also did not export the methods expected by the WASI spec.

Updating `wasi:http` `RequestOptions` to  properly handle nano/milliseconds

---

crates/js-component-bindgen/src/esm_bindgen.rs
crates/js-component-bindgen/src/function_bindgen.rs
crates/js-component-bindgen/src/names.rs
crates/js-component-bindgen/src/transpile_bindgen.rs
docs/src/optimized-host-bindings.md
package.json
xtask/src/build/jco.rs

After further discussion with @alexcrichton it turns out the resource map structure is still not quite right in the Jco model.
This updates the existing resource map functionality to instead operate on a resource map constructed per individual function.

fix: resource map per function

---

README.md

This commit updates the package name for the `preview-shim` package in the README.md file which I think might be a typo.

docs: rename preview-shim package name in README

---

packages/preview2-shim/lib/io/worker-http.js

Follow-on to https://github.com/bytecodealliance/jco/pull/408's timeout changes, fixing the granularity of `betweenBytesTimeout` and `firstByteTimeout` as well.

fix: timeout for betweenBytesTiemout and firstByteTimeout

---

package.json

Bumps the preview2-shim version in Jco to 0.16.1, and goes back to semver now that this is stable.

preview2-shim: update to 0.16.1

---

crates/js-component-bindgen/src/transpile_bindgen.rs

Resolves https://github.com/bytecodealliance/jco/issues/298 in throwing an error for attempting to construct a non-constructible resource.

feat: non-constructible resource error

---

package.json
test/cli.js
test/preview2.js

Updates the ComponentizeJS tests to the latest version, fixing the Windows support.

deps: update ComponentizeJS in tests

---

crates/js-component-bindgen/src/intrinsics.rs
crates/js-component-bindgen/src/transpile_bindgen.rs

In JS environments that do not support the `FinalizationRegistry`, this conditionally checks that it exists without assuming it when integrating into resource GC disposal.

feat: conditionally support FinalizationRegistry

---

crates/js-component-bindgen/src/ts_bindgen.rs
packages/preview2-shim/types/interfaces/wasi-filesystem-types.d.ts
packages/preview2-shim/types/interfaces/wasi-http-types.d.ts
packages/preview2-shim/types/interfaces/wasi-io-error.d.ts
packages/preview2-shim/types/interfaces/wasi-io-poll.d.ts
packages/preview2-shim/types/interfaces/wasi-io-streams.d.ts
packages/preview2-shim/types/interfaces/wasi-sockets-ip-name-lookup.d.ts
packages/preview2-shim/types/interfaces/wasi-sockets-tcp.d.ts
packages/preview2-shim/types/interfaces/wasi-sockets-udp.d.ts

This fixes a TS generation bug, where resource methods would not get doc comments properly outputted.

fix: ts resource method docs

---

crates/js-component-bindgen/src/ts_bindgen.rs
packages/preview2-shim/types/interfaces/wasi-http-types.d.ts
packages/preview2-shim/types/interfaces/wasi-io-streams.d.ts
packages/preview2-shim/types/interfaces/wasi-sockets-udp.d.ts

This fixes a bug with the TypeScript generation where multiple runs of the same type generation would generate types in different orderings, reinstating deterministic output!

fix: typescript generation determinism

---

crates/js-component-bindgen-component/src/lib.rs
src/api.js
src/cmd/transpile.js
src/jco.js
test/api.js
test/cli.js

Follow-up to https://github.com/bytecodealliance/jco/pull/423, supporting types generation via a new `types` function also supported in the CLI via eg `jco types ./wit-dir -o ./types` to generate the types in the directory `./types` from the WIT folder at `./wit-dir`.

Type generation with WIT folder support

---

crates/js-component-bindgen/src/intrinsics.rs

Handle 0 is reserved for the sentinel value, but resource rep can be 0 IIUC
> Upon initialization, table element 0 is allocated and set to None, effectively
> reserving index 0 which is both useful for catching null/uninitialized
> accesses and allowing 0 to serve as a sentinel value.
> https://github.com/WebAssembly/component-model/blob/main/design/mvp/CanonicalABI.md#runtime-state

Don't need to check for non-zero resource rep

---

crates/js-component-bindgen/src/transpile_bindgen.rs
test/commands.js

Fixes a syntax error in not closing the statement correctly when outputting `definedResourceTables`.
We need a new output source to define the concept of defined intrinsics, which is now carried through properly to ensure scoping in all instantiation outputs.
Resolves https://github.com/bytecodealliance/jco/issues/436.

Fix syntax error with defined intrinsics

---

README.md

This commit adds the missing `jco types` subcommand to the README.
This command is extraordinarily useful compared to the previous flow.

docs: update jco usage output in README

---

crates/js-component-bindgen/src/intrinsics.rs

Recent dlmalloc-rs started validating that deallocation size is same as the size that was allocated.
https://github.com/alexcrichton/dlmalloc-rs/blob/0.2.6/src/dlmalloc.rs#L1187
Since canonical abi string does not have "capacity" concept separate from "length", we don't have a way to tell how much memory was allocated to the buffer owner. So, canonical abi always assumes that "length" is the same as "capacity" and deallocates the buffer with the "length" size.
This means that if we overallocate the buffer and return the buffer with a length less than the allocated size, dlmalloc-rs validation will fail.
```console
$ rustc --version
rustc 1.80.0-nightly (791adf759 2024-05-21)
$ cat main.rs
fn main() {
let foo = std::env::var("FOO");
println!("FOO: {:?}", foo);
}
$ rustc …
```

fix: don't overallocate string buffer while encoding into utf8

---

xtask/src/generate/tests.rs

Reenables the Windows test suite, which got disabled with some Deno test refactoring.

fix: windows tests

---

README.md

Removes the old note that Node.js WASI support is still undergoing stabilization.

update readme for Node.js WASI stability

---

packages/preview2-shim/lib/nodejs/filesystem.js

When an application attempts to open a non-existent path such as `//foo/bar/baz` on Windows, Node generates an error of the form:
```
{
errno: -4094,
syscall: 'open',
code: 'UNKNOWN',
path: '//foo/bar/baz'
}
```
Prior to this commit, that error would be re-thrown, causing Wasm execution to trap.  Now we convert it to a "no-such-device" error instead.

translate errno=-4094 errors to "no-such-device" on Windows

---

crates/js-component-bindgen/src/transpile_bindgen.rs

The `js_instrinsics` should be defined under the `instantiate` function. Otherwise we get the following error:
```
dist/component/ruby.component.js:73
if (definedResourceTables[toTid]) return rep;
^
ReferenceError: definedResourceTables is not defined
```
https://github.com/ruby/ruby.wasm/actions/runs/9708747430/job/26796119275?pr=479#step:14:302

Fix definedResourceTables ReferenceError with instantiation mode

---

docs/src/example.md

This removes the reference to `--enable-stdout`, which isn't a CLI option since around `1.2.0`.
W/ this said, it looks like `--enable-stdout` was removed when `--disable-features` was added. Does that imply `stdout` is now enabled by default? I was trying to test that out and couldn't get `console.log` to work. Submitted an issue to discuss it here: https://github.com/bytecodealliance/jco/issues/457 .

Update Outdated Docs

---

packages/preview2-shim/lib/nodejs/http.js

allow port numbers up to 65535 in `OutgoingRequest.setAuthority`

---

src/cmd/transpile.js

Fixes the jsdoc type definition, resolving https://github.com/bytecodealliance/jco/issues/462.

fix: TypeScript types

---

package-lock.json

The inconsistent lock file lead `npm ci` fails when vendoring jco as submodule

Update package-lock.json by `npm install`

---

crates/js-component-bindgen/src/ts_bindgen.rs

Fixes https://github.com/bytecodealliance/jco/issues/472
In async mode, `getCoreModule` should have `Promise<WebAssembly.Module>` return type.

Fix: `getCoreModule` type for async `instantiate`

---

crates/js-component-bindgen/src/function_bindgen.rs

This fixes a bug with ComponentizeJS bindgen on the Jco upgrade path for it.

fix: ComponentizeJS bindgen bug

---

crates/js-component-bindgen/src/ts_bindgen.rs
test/fixtures/wits/issue-480/issue-480.wit
test/typescript.js

Closes #480 
This changes the types generated for a WIT `list` to use `Array<>` syntax, which allows for something like `option<foo>` to be expanded to `foo | undefined` without generating the wrong type signature. Using `Array<>` also avoids the need to wrapping too much stuff in parens.

fix: Wrap lists in Array to handle optional types

---

Cargo.lock
Cargo.toml
crates/js-component-bindgen-component/src/lib.rs
crates/js-component-bindgen-component/wit/js-component-bindgen.wit
crates/js-component-bindgen/Cargo.toml
crates/js-component-bindgen/src/lib.rs
crates/js-component-bindgen/src/ts_bindgen.rs
crates/wasm-tools-component/src/lib.rs
crates/wasm-tools-component/wit/wasm-tools.wit
src/cmd/transpile.js
src/jco.js
test/cli.js
test/fixtures/wits/feature-gates-unstable.wit
test/fixtures/wits/feature-gates.wit
test/helpers.js
test/preview2.js
test/test.js
test/wit.js

This PR updates `jco` to support the `@since`, `@after` and `@unstable` annotations as implemented by the upstream Rust tooling.
Currently there are a few issues left to address:
- ~~https://github.com/bytecodealliance/wasm-tools/commit/01bec9c8adb491a591447b52ebf353babcd8b8f1~~
- ~~https://github.com/bytecodealliance/wasm-tools/commit/10d2e21b2171cf2a2227f9de04ac89985042a5f0~~

feat: support semver aware exclusions

---

crates/js-component-bindgen/src/function_bindgen.rs

Patches a regression just introduced in https://github.com/bytecodealliance/jco/pull/487, fixing function bindgen support for multiple returns.

fix: multi-return regression

---

crates/js-component-bindgen/src/function_bindgen.rs
crates/js-component-bindgen/src/transpile_bindgen.rs

This fixes another issue with error returns in the new post-return handling following https://github.com/bytecodealliance/jco/pull/487 and https://github.com/bytecodealliance/jco/pull/489 (again caught and tested through ComponentizeJS test suite, and another reason to upstream it here).

fix: post-return on error return bindgen

---

src/cmd/opt.js
src/cmd/run.js
src/cmd/transpile.js

the existing hard-coded paths fail when the project is installed/ran via a source/git dependency, instead of `npx`, because `jco`'s own dependencies are installed in parent `node_modules` directories.
This change reuses NodeJS's own resolution mechanism to find the correct paths directly, without having to hardcode them, which should work everywhere.
---
NOTE: there are two tests failing, because (I suspect) they are using a custom directory layout that doesn't follow `node_modules/*`. I wasn't able yet to figure out how they are set up, and I want to make sure this is the right change first.
Please let me know if you have any suggestions.

use `require.resolve` shim instead of hard-coded paths

---

packages/preview2-shim/lib/browser/filesystem.js

Otherwise, we get the following error:
```
filesystem.js:44 Uncaught TypeError: Cannot read properties of undefined (reading 'create')
at getChildEntry (filesystem.js:44:47)
at Descriptor.statAt (filesystem.js:201:19)
at trampoline75 (ruby.js:1430:38)
at wit-component:shim.indirect-wasi:filesystem/types@0.2.0-[method]descriptor.stat-at (ruby.core106.wasm:0x1e1)
```

fix: pass open flags to getChildEntry in statAt

---

packages/preview2-shim/lib/browser/cli.js
packages/preview2-shim/lib/browser/filesystem.js

Close https://github.com/bytecodealliance/jco/issues/497
I'll try to make time to set up more test suites for the browser shim, but for now, just make it work with ruby.

Set `/` as the default initial working directory for browser p2 shim

---

packages/preview2-shim/lib/browser/cli.js

Fix for #501
`console.log` and `console.error` append a new line to the printed output.
If the buffer to be printed ends with a new line, remove it before printing.

Fix double newline using browser shim

---

crates/js-component-bindgen/src/transpile_bindgen.rs

Abscence of return causes a hidden exception, which is handled by `catch` block and then passed to the `reject` callback while promise is already resolved
`TypeError: Cannot read properties of undefined (reading 'then')`
at:
```js
value.then(nextVal => done ? resolve() : runNext(nextVal), reject);
// ^
```
You can reproduce it by following this [guide](https://component-model.bytecodealliance.org/language-support/javascript.html#running-a-component-from-javascript-applications) and running wasm component in nodejs with this handler (and yeah, "multipleResolves" event is [deprecated](https://github.com/nodejs/node/issues/41554) but it's the only way I know of to observe this bug)
```js
process.on('multipleResolves', (...args) =>{
console.log('multipleResolves', args)
})
```

Fix hidden exception in `runNext`

---

crates/js-component-bindgen/src/transpile_bindgen.rs

Resolves https://github.com/bytecodealliance/jco/issues/517 where the resource wasn't yet processed at trampoline generation, by doing trampoline generation later on after exports.

fix: resource map being populated after trampoline

---

package-lock.json
package.json
test/cli.js

Updates to 0.14.0 supporting WASI@0.2.2 correctly, and reenables the ComponentizeJS test.

deps: update to ComponentizeJS@0.14.0

---

crates/js-component-bindgen/src/function_bindgen.rs
crates/js-component-bindgen/src/transpile_bindgen.rs

Fixes some bugs with the top-level resource bindgen introduced in https://github.com/bytecodealliance/jco/pull/525.

fix: top-level resource bindgen

---

README.md
crates/js-component-bindgen-component/src/lib.rs
crates/js-component-bindgen-component/wit/js-component-bindgen.wit
crates/js-component-bindgen/src/transpile_bindgen.rs
crates/js-component-bindgen/src/ts_bindgen.rs
src/cmd/transpile.js
src/jco.js
test/api.js
test/cli.js
xtask/src/build/jco.rs
xtask/src/generate/wasi_types.rs

Adds a `--declare-imports` option to the `jco types` command.
Closes #439

feat: add module declaration support

---

crates/js-component-bindgen/src/ts_bindgen.rs

Closes https://github.com/bytecodealliance/jco/issues/543

generate private resource constructors when none are defined

---

Cargo.lock
Cargo.toml
crates/js-component-bindgen/src/core.rs
xtask/Cargo.toml
xtask/src/generate/webidl_tests.rs

Now that [`webidl2wit`](https://crates.io/crates/webidl2wit) is a published crate, we can use the released version (and later use [`webidl2wit-cli`](https://crates.io/crates/webidl2wit-cli) in docs and tests!)

chore(deps): use published version of webidl2wit

---

test/helpers.js
test/test.js

This commit fixes the issue with tests that was causing folders to be picked up when present in the test component fixtures, along with some quality-of-life changes for error output

fix(tests): evaluation of fixture binaries

---

package.json

This commit increases the timeout for windows failures in test/cli.js, which on the windows runner *sometimes* took slightly too long.
The runs below (done on my fork) are what surfaced the issue -- the failure is just intermittent on CI runner perf:
(i.e. the exact same code would *sometimes complete* and sometimes not, when the tests were severely reduced.
[EDIT] With the timeout raised here's how long the componentize test w/ AOT took:
```
✔ Componentize (152987ms)
```
Ideally we should *also* have a non-AOT componentize test w/ transpile mapping but I'll settle for getting CI back to green for now

fix(tests): intermittent windows CI timeout

---

Cargo.lock
Cargo.toml
crates/js-component-bindgen-component/Cargo.toml
crates/js-component-bindgen/Cargo.toml
crates/js-component-bindgen/src/core.rs
crates/js-component-bindgen/src/function_bindgen.rs
crates/js-component-bindgen/src/transpile_bindgen.rs
crates/js-component-bindgen/src/ts_bindgen.rs
crates/wasm-tools-component/Cargo.toml
crates/wasm-tools-component/src/lib.rs
test/api.js
test/cli.js

This PR does a few things: 
- upgrade upstream deps to `x.224.x` variants
- light refactoring around use of dependencies to avoid unnecessary code being pulled in
- add codegen implementation for new flush (this was necessary due to checks that would cause build to fail w/ updated upstream deps)
- mark places where async impl will be needed

chore(deps): update upstream deps

---

Cargo.lock
Cargo.toml
test/api.js
test/cli.js

This commit updates the repo to 225.x and related in upstream wasmtime crates.
This was found to be necessary thanks to @calvinrp for charging ahead on trying built async components locally.

chore(deps): update to v225.0 of wasmtime upstream

---

.github/workflows/docs.yml
docs/book.toml
docs/src/SUMMARY.md
docs/src/wit-type-representations.md

Resolves https://github.com/bytecodealliance/jco/issues/418.

feat(docs): add docs for object conversions

---

crates/js-component-bindgen/src/intrinsics.rs

Adds ArrayBuffer, TextDecoder, TextEncoder, to global names.
Currently, components that export resources with any of these names override JS's types of the same name. This causes problems in Jco glue code, as these types are used there.

Added JS globals ArrayBuffer, TextDecoder, TextEncoder

---

.github/workflows/docs.yml

Just noticed that the [jco book](https://bytecodealliance.github.io/jco) is not accessible -- it looks like the path of the generated code from mdbook was wrong -- the generated code now lives in `docs/book/html`, I think due to the introduction of `mdbook-linkcheck`.

fix(docs): generation of gh pages

---

.gitignore

This commit ensures that package-lock.json isn't checked in, as npm version v7 and up uses "hidden" lockfiles in node_modules.

chore: ensure package-lock.json isn't checked in

---

test/browser.js

This is an attempt to fix https://github.com/bytecodealliance/jco/issues/600.

fix: wait 500ms before running a browser request

---

src/cmd/componentize.js
src/jco.js

This PR goes in concert with https://github.com/bytecodealliance/ComponentizeJS/pull/206

feat: add min stack size setting for AOT

---

src/cmd/componentize.js
src/cmd/transpile.js

This PR adds a hint that shows users when they use an *incorrect* WIT path (ex. using `wit/world.wit` when there are deps, and `wit/` should be used).
Ideally we can automatically determine this for them in the future (ex. when the WIT path is optional), but for now at least common errors should have good guiding error messages.

feat(ux): add hint for incorrect witPath setting

---

docs/src/wit-type-representations.md

In https://bytecodealliance.github.io/jco/wit-type-representations.html#options-option
before
after
The `|` was not rendering correctly inside code blocks within tables when processed by `mdbook`. https://github.com/rust-lang/mdBook/issues/637
Ideally, this should be addressed by the upstream. The root cause of this problem in `pulldown-cmark` has recently been fixed. https://github.com/pulldown-cmark/pulldown-cmark/issues/356 However, `mdbook` seems to expose the `pulldown-cmark` types as a public API, and is currently facing difficulties updating its dependencies. https://github.com/rust-lang/mdBook/pull/2386
Therefore, the upstream fix may not available in any time soon.
As a workaround for the time being, use `<code>` tag instead of code blocks in tables with `|`.

docs: fix rendering for | in code blocks in table

---

Cargo.lock
Cargo.toml

wasmtime-environ 31.0.0 adds support for exception tags. https://github.com/bytecodealliance/wasmtime/pull/10251
Previously, exception tags were not supported, and attempting to transpile a component binary containing a tag would fail by hitting `unreachable`. Updating `wasmtime-environ` to 31.0.0 enable to transpile binary with exceptions.

chore(deps): Update wasmtime-environ to 31.0.0

---

examples/components/add/package.json
examples/components/http-hello-world/package.json
examples/components/node-fetch/package.json
examples/components/string-reverse-upper/package.json
examples/components/string-reverse/package.json
examples/components/webidl-book-library/package.json

This commit re-adds the componentize-js dep for examples, as when building components jco will dynamically import.

chore(examples): re-add componentize-js dep for examples

---

CHANGELOG.md
examples/components/add/package.json
examples/components/http-hello-world/package.json
examples/components/node-fetch/package.json
examples/components/string-reverse-upper/package.json
examples/components/string-reverse/package.json
examples/components/webidl-book-library/package.json
package.json

This is a release prep branch for `jco` release `v1.11.0`.
To ensure this release is ready to be merged:
After merging this PR, please do the following:

release: jco v1.11.0

---

package.json

This commit fixes the automated release issue caused by `obj/*` files not being included in the packaged tarball. This step should have been pre pack rather than prepublish.

fix: make package build steps prepack

---

src/cmd/run.js

Small fix, it did an append to a const variable. This crashes the error handling.

fix: appending to const value raises error

---

docs/src/wit-type-representations.md

Updated the representation of variants in the documentation to use `val` instead of `data`.

fix(docs): variants with associated data uses `val`

---

.github/workflows/main.yml

This commit changes puppeteer to always be installed, in case the version is missing

chore: always install puppeteer

---

.github/dependabot.yml
.github/workflows/create-release-pr.yml
.github/workflows/release.yml
.github/workflows/tag-release.yml
README.md
commitlint.config.mjs
docs/src/contributing.md
packages/preview3-shim/cliff.toml

The changes in here are un-tested (we haven't done a release of p3-shim), but should generally work the same in CI (we can test when release `0.1.0-rc.0` of `preview3-shim` and have the appropriate repos, creds, etc in place).

chore(p3-shim): add release automation, docs for p3-shim

---

crates/js-component-bindgen/src/intrinsics.rs
crates/js-component-bindgen/src/transpile_bindgen.rs

This commit adds the initial implementation of canon yield, *without* full implementation of the Task primitive.
While yield is not fully operational with just this PR, it matches the spec pseudo-code, and has the appropriate internal wait stubbed out.

feat(bindgen): implement yield

---

packages/preview3-shim/lib/nodejs/workers/tcp-worker.js
packages/preview3-shim/test/tcp.test.js

Small patch that ensure that we close the socket's server explicitly on symbol dispose. This also ensures that accept connection stream will be closed.

feat(p3-shim): close socket's server explicitly on symbol dispose

---

eslint.config.mjs
packages/jco/package.json
packages/jco/src/api.js
packages/jco/src/browser.js
packages/jco/src/common.js
packages/jco/src/jco.js
packages/jco/src/ora-shim.js
packages/jco/test/api.js
packages/jco/test/async.browser.js
packages/jco/test/async.js
packages/jco/test/browser.js
packages/jco/test/cli.js
packages/jco/test/codegen.js
packages/jco/test/commands.js
packages/jco/test/common.js
packages/jco/test/fixtures/component-gen/import-fn.js
packages/jco/test/fixtures/componentize/source.js
packages/jco/test/fixtures/componentize/wasi-http-proxy/source.js
packages/jco/test/fixtures/idl/console.test.js
packages/jco/test/fixtures/idl/dom.test.js
packages/jco/test/helpers.js
packages/jco/test/runtime.js
packages/jco/test/typescript.js
packages/jco/test/wit.js

The glob `"lint": "eslint -c ../../eslint.config.mjs ./src/**/*.js",` seems to not pick up the files recursively. I used `"lint": "eslint -c ../../eslint.config.mjs --ext .js src test"` instead.

fix(jco): run linter on jco package source code

---

packages/jco/src/cmd/componentize.js
packages/jco/src/jco.js

This commit makes use of new functionality in componentize that enables passing in more debug options, and outputs information from debugging during the jco build.
NOTE: this depends on some unreleased code for `componentize-js`:
https://github.com/bytecodealliance/ComponentizeJS/pull/203

refactor: pass more debug options to componentize

---

packages/jco/src/cmd/transpile.js
packages/jco/src/cmd/types.d.ts
packages/jco/src/cmd/types.js
packages/jco/src/common.d.ts
packages/jco/src/common.d.ts.map
packages/jco/src/common.js
packages/jco/src/jco.js

This commit separates out type generation to another file from the transpilation logic, but keeps the exports that were previously part of transpile in place to ensure backwards compatibility.

refactor(jco): move type generation functions to separate file

---

crates/js-component-bindgen/src/ts_bindgen.rs
packages/jco/src/cmd/transpile.js
packages/jco/src/cmd/types.js
packages/jco/src/common.d.ts
packages/jco/src/common.d.ts.map
packages/jco/src/common.js
packages/jco/src/jco.js
packages/jco/test/p3/transpile.js

This commit enables generation of async exports when building guest types for a component. Since an async export requires JSPI on the part of the host/embedding environment, we also require that async-export JSPI be enabled as well.
Resolves #623

feat(jco): support async export generation for guest-types

---

package-lock.json

This commit updates componentize-js to v0.18.5 which resolves an issue
with a mismatch between valid configurations for wasmtime and
componentize-js -- to enable caching, a TOML file that looks like the
following can be used (at `$HOME/.config/wasmtime/config.toml`):
```
[cache]
```
Resolves #715

chore(jco): update componentize-js to v0.18.5

---

packages/jco-transpile/package.json
packages/jco-transpile/src/common.js

This commit removes the `chalk-template` dependency. While we were not vulnerable to the upstream malicious code injection that happened to chalk and related deps, the chalk dependency is no longer needed when using Node 20.x and above.
For node versions 20 or other platforms that do not have the dependency, we use a polyfill that simply loses the colored output.
This is a breaking change in a sense as output will change and users that are on node 18 and rely on the color output will get output that is inconsistent from before, but removing this dependency is a high priority at this point and the repercussions are likely minor from the light semver breakage.
Link: https://github.com/chalk/chalk/issues/656

refactor(transpile): remove chalk dependency
